dist: trusty
language: node_js
node_js:
  - 8
  - 10
env:
  - CI=true
cache:
  yarn: true
  directories:
    - .npm
install:
   - npm install
script:
  - npm test
before_deploy:
 - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
 - docker build -t $DOCKER_IMAGE
 - docker push -t $DOCKER_IMAGE