dist: trusty
language: node_js
node_js:
  - 8
env:
  - CI=true
cache:
  yarn: true
  directories:
    - .npm
install:
   - npm install
script:
  - npm test
after_script:
 - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
 - docker build -t $DOCKER_IMAGE .
 - docker push $DOCKER_IMAGE
 - echo $MACHINE_KEY > MACHINE_KEY.pem
 - scp -i MACHINE_KEY.pem -o "StrictHostKeyChecking no" docker-compose.yml MACHINE_USER@MACHINE_ADDRESS:~/
 - rm -f MACHINE_KEY.pem